### ISSUE TITLE
Make Smart Dashboard more specific - Cohen

### ISSUE THREAD

**Issue by boinary** [FRC-1721/pre2020season#14]
In `src/main/java/frc/robot/subsystems/Drivetrain.java` The smart dashboard, after testing, only reported turning when going backward and reported `scurt` when doing anything else. I recommend adding more descriptive phrases. For example, `moving left` or `moving right`.

**Comment by KenwoodFox** [comment]
Here is the relevant code in case anybody wanted to view
https://github.com/FRC-1721/pre2020season/blob/e20f0f770e8f6336864faab2d43b4dac2713ae30/src/main/java/frc/robot/subsystems/Drivetrain.java#L28-L32

**Comment by cocothebam** [comment]
the problem has been fixed and switched to different terms
